version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-nginx-network
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://db:3306",
        "-timeout",
        "20s",
        "npm",
        "run",
        "start",
      ]

    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      - node-nginx-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./node/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=node
      - MYSQL_PASSWORD=node
      - MYSQL_DATABASE=nodejs
    networks:
      - node-nginx-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8099:8080
    networks:
      - node-nginx-network

networks:
  node-nginx-network:
    driver: bridge
